version: '3.9'

services:
  web:
    container_name: conciergerie_prod_web
    build: 
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8800:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: conciergerie_db
    image: postgres:14.0-alpine
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
 
  nginx:
    container_name: conciergerie_nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
