"""
Django settings for conciergerie project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.db import models
from django.utils.translation import gettext_lazy as _
from celery.schedules import crontab
import environ
from datetime import timedelta
# Initialise environment variables
env = environ.Env()
environ.Env.read_env()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR    = Path(__file__).resolve().parent.parent
# Directory project au meme niveau de settings.py
PROJECT_DIR = Path(__file__).resolve().parent
HOST = env("HOST")
BASE_URL = f"http://{HOST}"  # ou l'URL de votre serveur en production


ADMINS = (
    # ('Your Name', 'your_email@example.com'),
)

MANAGERS = ADMINS


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-fumu!8#a64vb1b55&oum7bhexxp=u3o&(t-6b+qykitij(3wj*"
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '168.231.108.40', 'atlass.fr', 'netatlass.com', 'www.atlass.fr', 'www.netatlass.com',
                 'conciergerie.netatlass.com', 'www.conciergerie.netatlass.com', ]


# settings.py  ou  .env.prod
CSRF_TRUSTED_ORIGINS = [
    "https://conciergerie.netatlass.com",
    "https://www.conciergerie.netatlass.com",
]

# conciergerie/.env.prod
## CSRF_TRUSTED_ORIGINS=https://conciergerie.netatlass.com,https://www.conciergerie.netatlass.com

SITE = 1
SITE_ID = 1
# email backend 
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # new

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "core.CustomUser"



# Application definition

INSTALLED_APPS = [
   
     # apps par defaut
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters", # new
    'django.contrib.sites',  # new
    'django.contrib.humanize', # new
    'corsheaders',
     ## import / Export
    'import_export',
    ## Django Slick reportings
    "slick_reporting",
    "crispy_forms",
    "crispy_bootstrap4",
    # 3rd-party apps
    'rest_framework', # new
    'rest_framework.authtoken',
    "dj_rest_auth",
    'drf_spectacular', # Générateur automatique de documentation OpenAPI 3 pour DRF
    # debug tools
    'debug_toolbar', # newo
    'django_extensions',
    # User Authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # sql explorer
    'explorer',
    # local
    'django_celery_beat',
     # local apps
    'core', # common models 
    'staff',
    'fullcalendar', # fullcalendar scheduler
    ## 'slick_report', 
    ## 'pandas_report',
    ##'services_menage', 
    "conciergerie",
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # Doit être en haut
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',  # Doit être en haut, avant CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
    # debug 
    'debug_toolbar.middleware.DebugToolbarMiddleware', # new
    "core.middleware.LoginRequiredMiddleware",  # 👈 ajouté ici
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        "NAME": env("DATABASE_NAME"),
        "USER": env("DATABASE_USER"),
        "PASSWORD": env("DATABASE_PASSWORD"), 
        "HOST" : env( "HOST"),
        'PORT': '5432',
    }
}

"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
"""


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# In a Windows environment this must be set to your system time zone.
TIME_ZONE = 'Europe/Paris'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'Fr-fr'

DEFAULT_CHARSET='UTF-8'

TIME_ZONE = 'UTC'
# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = True

# If you set this to False, Django will not use timezone-aware datetimes.
# Lorsque USE_TZ vaut True et que la base de données ne gère pas les fuseaux horaires (par ex. SQLite, MySQL, Oracle), Django lit et écrit les dates/heures en heure locale en fonction de cette option quand elle est définie et en UTC si elle ne l’est pas.

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


STATIC_URL = "static/"
# Chemin où les fichiers statiques seront collectés (utilisé pour le déploiement)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'static', 'bootstrap_agency'),
    # os.path.join(BASE_DIR, 'media'),
    #  os.path.join(BASE_DIR, 'media', 'upload'),
]

## 
# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/4.0/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery configuration
# Celery Beat settings

# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'  # Assurez-vous que le fuseau horaire 
#
# Ancienne configuration (encore supportée jusqu'à Celery 6.0)
CELERY_BROKER_CONNECTION_RETRY = False

# Nouvelle configuration pour Celery 6.0 et au-delà
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = False


CELERY_BEAT_SCHEDULE = {
    'create-events-daily': {
        'task': 'services_menage.tasks.service_checkin_task',
        'schedule': crontab(hour=22, minute=18),
        #'schedule': crontab(minute='*/1'),  # Exécute toutes les 10 minutes
    },
    'update-resa-status': {
        'task': 'services_menage.tasks.cron_update_reservation_status',
        #'schedule': crontab(minute='*/1'),  # Exécute toutes les 10 minutes
        'schedule': crontab(hour=22, minute=18),
    },
}



REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES' : [
        ##'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTIFICATION_CLASS' : [
        'rest_famework.authentification.SessionAuthentification', 
        'rest_framework.authentification.BasicAuthentification',
        'rest_framework_simplejwt.authentication.JWTAuthentication', 
        'rest_framework.authtoken',
    ] 
    
}

# DJANGO REST FRAMEWORKS

CORS_ORIGIN_ALLOW_ALL = True # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    "http://localhost:8000",
    'http://localhost:8080',
] # If this is used, then not need to use `CORS_ORIGIN_ALLOW_ALL = True`
CORS_ORIGIN_REGEX_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8080',
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_URL = "/accounts/login/"

"""
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
} 
"""

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]


# Autoriser toujours la méthode OPTIONS (prévol)
CORS_ALLOW_METHODS = list(default_methods := [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
])

# Si tu utilises les cookies/session, aussi autoriser les credentials
CORS_ALLOW_CREDENTIALS = True

# Autoriser certains headers si besoin (ex : Authorization)
CORS_ALLOW_HEADERS = list(default_headers := [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
])

LOGIN_REDIRECT_URL = "/"
LOGOUT_URL = "/accounts/login/"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            #'level': 'DEBUG',
        },
    },
}

# Report + Crispy
CRISPY_TEMPLATE_PACK = "bootstrap4"
# SQL Explorer
#EXPLORER_PERMISSION_VIEW = lambda u: u.is_staff
#EXPLORER_PERMISSION_CHANGE = lambda u: u.is_superuser

# Configurer DRF pour utiliser JWT  


REST_FRAMEWORK = {
    
    'DEFAULT_PERMISSION_CLASSES' : [
        #'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTIFICATION_CLASS' : [
        'rest_famework.authentification.SessionAuthentification', 
        'rest_framework_simplejwt.authentication.JWTAuthentication', 
        "rest_framework.authentication.TokenAuthentication",
        #'rest_framework.authentification.BasicAuthentification',
        ##'rest_framework_simplejwt.authentication.JWTAuthentication', 
        ##'rest_framework.authtoken',
    ],
    # Schema pour la documentation automatique
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 
#-----------
# Paginations 
#-----------
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'Conciergerie Mon API Django',
    'DESCRIPTION': 'Documentation de mon API',
    'VERSION': '1.0.0',
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # adapte en fonction du port
    "http://localhost:8000",
    "http://localhost:8080",
]
CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    "http://localhost:8000",
    'http://localhost:8080',
    'http://localhost:5173',
] # If this is used, then not need to use `CORS_ORIGIN_ALLOW_ALL = True`
CORS_ORIGIN_REGEX_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8080',
    'http://localhost:5173',
]
# DJANGO REST FRAMEWORKS

CORS_ORIGIN_ALLOW_ALL = True # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ALLOW_ALL_ORIGINS = True  # Pour le développement uniquement

## CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_CREDENTIALS = True # If you are using cookies/session authentication
# duree de vie des tokens
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

